### ISSUE TITLE
Daylight saving time (end of March) - tasks are 1 day shorter

### ISSUE THREAD

**Issue by mihaibar** [taitems/jQuery.Gantt#119]
Hi all,

(newbie here)

This issue is similar to #41 regarding the daylight saving time. It seems that any task going over the 29-30th of March, 2014 will appear 1 day shorter in the Gantt chart.

Cheers,
Mihai

**Comment by simonhutchings** [comment]
This is closed, but still the same on the latest version. Anything crossing the time change loses a day. Great plugin by the way, used it for a couple of projects

**Comment by usmonster** [comment]
Hi @simonhutchings, glad you find this plugin useful! This issue was closed in favor of the other open issues on the same subject: #41 and #95. It's a known bug that is unfortunately still around, though it is set to be fixed in the next major release.
