### ISSUE TITLE
Fixed bar as a separator

### ISSUE THREAD

**Issue by PeterFour** [taitems/jQuery.Gantt#148]
Is it possible to create a fixed width separator as an item bar  which will be static while scrolling ?

**Comment by usmonster** [comment]
Hello from 2019!

For your workaround, you can add a class to your separator item (make sure `customClass` is on the returned data) and use CSS to make it fixed. I hope this helps!

Since I don't think we'll implement this behavior in the plugin, I'm closing the issue.
