### ISSUE TITLE
Increase zoom to mins/secs

### ISSUE THREAD

**Issue by smiller393** [taitems/jQuery.Gantt#159]
I am looking at add an enhancement to this that will allow users to view items down to the minute/second by zooming in further. Currently the most detailed view is hour by hour, but after this is added in, maybe the user could zoom in to view second by second. This will allow for more of a one day timeline of events that could be very useful in many projects. 

The goal would be to make it similar the timeline chart in Google's visualization api:
https://developers.google.com/chart/interactive/docs/gallery/timeline#ControllingColors

I plan on starting this once I finish implementing what was started in pull req: taitems/jQuery.Gantt#117

If anyone has ideas, opinions, or advise about this please let me know! I am hoping that this is somewhat of an easy change, so let me know if I am mistaken.

**Comment by smiller393** [comment]
With req #117 completed, I'm going to begin work on this change. Is this something that i should plan on pushing back to this project, or is it not a desired feature?

**Comment by usmonster** [comment]
I would say that the feature isn't in high demand, but I would still recommend that, if you do end up making the change for your app, definitely link to the fork/branch here. Thanks again!

**Comment by ascotthancock** [comment]
Hi smiller.

Did you ever get this feature developed? I definitely need this. I too am tracking tasks to the minute. Not the second, but the minute is a real requirement. I would be interested in testing anything you had enhanced in this area.

**Comment by animalillo** [comment]
I would love this feature too! I'm looking into using this for comparing times spent in different server processes for performance measurement.

**Comment by animalillo** [comment]
Would it be just adding another case on Date.prototype.getRepDate = function (scale) ?

**Comment by usmonster** [comment]
Following up on [my previous comment](https://github.com/taitems/jQuery.Gantt/issues/159#issuecomment-72731613), I'm closing this issue.

Feel free to comment with a link to a fork that implements this request for those who seek it!
