### ISSUE TITLE
Poll: Make this a jQuery UI widget?

### ISSUE THREAD

**Issue by usmonster** [taitems/jQuery.Gantt#160]
Should this plugin be adapted to be a jQuery UI Widget?

The assumption is that it will become more maintainable and extensible, and that most people who use the plugin as it is are likely are already using jQUI...

Everyone who has an opinion, please comment it here. (Perhaps it would be better off as a separate branch/project?)

**Comment by jacquesdev** [comment]
Yes! You have my vote!

**Comment by usmonster** [comment]
Not enough votes in the past 4 years(!), so closing!
