### ISSUE TITLE
Maximum resolution is hourly?

### ISSUE THREAD

**Issue by jnorris441** [taitems/jQuery.Gantt#165]
Is there a scale beyond hourly currently? 

I think the hourly view is rounding down to the nearest hour. If you put in an appointment for 4:00PM and 4:30PM, they show at the same position I believe.

**Comment by usmonster** [comment]
I think your root problem is covered by #47, which will be corrected in the next milestone. Please feel free to follow that issue and close this one. Thanks for reporting!
