### ISSUE TITLE
Create PDF 

### ISSUE THREAD

**Issue by AlexE86** [taitems/jQuery.Gantt#178]
Is it possible to export / save the gantt as pdf?
My Tests with html2pdf or html2canvas went wrong.

Best regards,

**Comment by usmonster** [comment]
Hi @AlexE86! Thakns for using the plugin. The feature you're requesting is currently beyond the scope of the project, so I'm closing the issue for now.

In the meantime, have you tried Mozilla's PDF.js : https://github.com/mozilla/pdf.js ?

**Comment by toandocoffee** [comment]
Hi Monster, 
Are this feature is still developing? 
Thank you

**Comment by usmonster** [comment]
Hi @toandocoffee! This feature request was closed, with the reason in the previous comment ☝️.
So, no, we're not developing the "Create PDF" feature. :)
Cheers!
