### ISSUE TITLE
Render empty date columns for clicking in future unreserved dates 

### ISSUE THREAD

**Issue by kobruleht** [taitems/jQuery.Gantt#182]
Demo in http://taitems.github.io/jQuery.Gantt/ shows only 3 days after last bar.

It is not possible to make reservation for month into future by clicking in column which is in month after last date which has value.

There should be parameter like minWidthInDays which specifies minimum width of grid in days. If source value range is smaller, empty day columns should be rendered in end.
Grid shuld have always at least specified number of day columns .
This allows  click in those columns to put reservation into future.

Or there should be way to specify dummy to/from dates in value property which forces  drawing empty date columns at end.

I fixed this by adding line

`element.dateEnd.setDate(element.dateEnd.getDate() + 30);`

in end of init as described in
https://github.com/taitems/jQuery.Gantt/issues/121  
There should be some parameter which allows to implement this, which passes value 30 instead of hard-coding it into js file.

![future](https://cloud.githubusercontent.com/assets/1274923/9023718/580449da-38b0-11e5-8fe2-b5badfccad01.png)

**Comment by teti14** [comment]
hi. I've solved adding this code in jquery.fn.gantt.js
//row(250) element.dateEnd = tools.getMaxDate(element);
var dt = new Date();
var month = dt.getMonth()+1;
var day = dt.getDate();
var year = dt.getFullYear()+3;
element.dateEnd = new Date(year,month,day);

**Comment by usmonster** [comment]
Hello! Thanks for opening this issue, though this feature is already planned. As you mention, it is partially covered by #121, but I think #143 is really what you are asking for. Please feel free to subscribe to either or both issues to track the progress or add your opinion. In the meantime, I will close this issue as a duplicate.

Thanks again for using the plug-in!
