### ISSUE TITLE
Programmatically accesing widget

### ISSUE THREAD

**Issue by bp-brainiak** [taitems/jQuery.Gantt#188]
how do I access to the widget programmatically in runtime?

**Comment by usmonster** [comment]
Hi @bp-brainiak! Technically it's not a true widget, in that you currently can't access or modify an instance after initialization.

Please refer to #160 (and vote/subscribe if you want it), which may address your needs. If you'd prefer something different, please clarify here or comment on #160, or create a new issue. (I'm closing this one, for now.)

Thanks for using the plugin!
