### ISSUE TITLE
how to create subtask

### ISSUE THREAD

**Issue by ssaurabhprdxn** [taitems/jQuery.Gantt#207]
- [x] write a story
- [ ] write a script
- [x] set cast and actor

**Comment by ssaurabhprdxn** [comment]
This is how we can create subtask.

**Comment by usmonster** [comment]
Hi @ssaurabhprdxn ! I don't understand what you're demonstrating or how it's relevant to this project, so I'm closing the issue. Feel free to comment again here if you have more relevant information.
