### ISSUE TITLE
Issue with Pagination

### ISSUE THREAD

**Issue by RajKumariAluri** [taitems/jQuery.Gantt#209]
The element data has complete data from all the pages.
Need to know the use of 
core.markNow(element);  
core.fillData(element, $dataPanel, $leftPanel);

As the data in the html is not filtering according to pagination ,both left panel and right panel data .

Please guide me where we need to set the row start and row end nos.

Regards,
RajKumari

**Comment by usmonster** [comment]
Thanks for opening an issue, and sorry for the delayed response! Can you please explain again what your issue is, including a link to a JSFiddle and attached screenshots? Your goals and the context aren't quite clear to me. Thanks!

**Comment by InYourHead** [comment]
@RajKumariAluri I had this issue too. **When you pass whrong parameter type (string instead of numeric**), the pagination will not work correctly after changing a page  -  it will display too many items on second/next pages.

I think you can close this issue.
