### ISSUE TITLE
Auto generated and customizable date date on index page 

### ISSUE THREAD

**Issue by yucatio** [taitems/jQuery.Gantt#215]
Hi @usmonster 
As we discussed in #198 ,
I made sample date automatically created on index page. It always includes current day.
Furthermore, data is customizable.
Can you please check 
https://yucatio.github.io/jQuery.Gantt/index.html
You can change date by clicking "Open data input form"

Changes are
https://github.com/yucatio/jQuery.Gantt/pull/5/files

If you like it, I will add this change to #200 .
To use bootstrap datetimepicker, it needs bower, is it OK?
If you don't like it, can you please tell me how to change it.

**Comment by usmonster** [comment]
Sorry for the very late response, but I ended up solving #104 with another approach (seen in #219).
Thank you again for your contributions!
