### ISSUE TITLE
Gantt chart displaying wrong date

### ISSUE THREAD

**Issue by ramremo** [taitems/jQuery.Gantt#216]
when i give the input 

to: "4/28/2016",
from: "4/10/2016",

The "from" date is correctly displayed but the "to " date is wrong  as shown in the fig.
i just noted it as an alignment mismatch, don't know how to correct it. 

![uploadgantt](https://cloud.githubusercontent.com/assets/17381669/25471242/c7de89fa-2b43-11e7-9b64-c84e4a27f501.JPG)

**Comment by usmonster** [comment]
Hi @ramremo! Thanks for using the plug-in.

Can you please let me know if you're using the version form the master branch (this may have been fixed)? Also, can you please provide a JSFiddle that demonstrates this issue (it's easier to debug than a screenshot ;) )? Finally, what time zone are you in (this may be related to another open bug)?

Thanks!

**Comment by ramremo** [comment]
hi , 
Have a look at this code : https://jsfiddle.net/ramkumarb/fdn2qr2c/ 
Indian Standard Time (IST)  UTC+05:30.

**Comment by usmonster** [comment]
@ramremo Indeed, it looks like this was fixed already on the master branch, which is not yet released but should still be safe to use in production. (See #102 for some backstory and #213 for the fix.)
Please see this updated JSFiddle, which uses the updated JS and CSS from the master branch:
https://jsfiddle.net/fdn2qr2c/1/

I'll close this issue for now, but feel free to comment if this solution (using the master branch) doesn't resolve your issue.

Thanks again for your report!
