### ISSUE TITLE
Export to Excel Functionality Request 

### ISSUE THREAD

**Issue by lmbdev** [taitems/jQuery.Gantt#217]
Hello.
Requesting for an export to excel or pdf or export as an image functionality of the gantt chart. This would be very helpful for us. Would implementing this functionality be possible? :)

Thanks in advance!

**Comment by usmonster** [comment]
Hello! We're currently not planning to implement this, but a pull request might be welcome!

In the meantime, please see #178 for a link to a project that might help you export as a PDF.
