### ISSUE TITLE
Request for Vertical Scroll Functionality

### ISSUE THREAD

**Issue by lmbdev** [taitems/jQuery.Gantt#218]
Hello, 

I'm asking if creating on vertical scroll within the chart is possible. This includes the feature of the date header to be frozen while scrolled down.

Sample scenario: If the items are set to be 50 per page and user scrolled down the page, date header will not be visible.

Please take a look at this screen shot:
![image](https://user-images.githubusercontent.com/31038997/31192203-26caf216-a973-11e7-944a-d8e576d35bf7.png)

In the red box is where the scroll to be placed. Once scrolled down, the left panel will also be scrolled down but the one in the green box will freeze so it will still be visible.

Kindly check if this is possible to be implemented. Thanks so much!

**Comment by usmonster** [comment]
Hello, and sorry for the long delay!

Thanks for requesting these features. They're actually already planned and are covered by #186 and #180, so please feel free to follow those issues and comment if you want to contribute to the conversation.

In the meantime, I'll close this one. :)
