### ISSUE TITLE
Popover overflow

### ISSUE THREAD

**Issue by zebond** [taitems/jQuery.Gantt#220]
How to set popover overflow over gannt container?

**Comment by usmonster** [comment]
Hello @zebond! The popover used in the demo comes from Bootstrap (3.x), and it's not a part of this plugin. You'd have to check [their documentation](https://getbootstrap.com/docs/3.3/javascript/#popovers-options). You should be able to get your desired behavior by specifying the `container` option, i.e. maybe use `body` or whatever container element wraps your chart.

Hope this helps! Closing the issue now.

**Comment by zebond** [comment]
Thanks! I did it with container option and it works great.
