### ISSUE TITLE
How can I put more options before the calendar?

### ISSUE THREAD

**Issue by a113f** [taitems/jQuery.Gantt#228]
Like, I have the name, desc, and I want to have one more that has two fields. one on top of the other and on the calendar can show. Just like in the picture.
![captura de tela 2019-01-29 as 12 36 23](https://user-images.githubusercontent.com/25732016/51919652-a88dbe80-23c2-11e9-9aa1-13e6c66b1f85.png)

**Comment by usmonster** [comment]
Hi @a113f. Thanks for your question. If I understand correctly, you can do what you're looking for by omitting the `name` from your second row's data.

You can see an example on the demo page:
http://taitems.github.io/jQuery.Gantt/ ([code](https://github.com/taitems/jQuery.Gantt/blob/master/index.html#L501-L517))

Please let me know if this answers your question.

**Comment by a113f** [comment]
Thanks so much. Yes, it did.
