### ISSUE TITLE
Issue on Year Displayed on the Header

### ISSUE THREAD

**Issue by lmbdev** [taitems/jQuery.Gantt#229]
When the data presented is starting on January 2019, the year on the header displays as 2018. 

![gantt issue](https://user-images.githubusercontent.com/31038997/51969153-a6a12980-24ae-11e9-88c4-f481d09455dd.PNG)

**Comment by usmonster** [comment]
Hi @lmbdev. Thanks for reporting this.

In this case, it would be helpful if you could provide a simple [JSFiddle](https://jsfiddle.net/) to demonstrate the issue.
(Please also make sure you're using the official source code from this repository.)

**Comment by usmonster** [comment]
Hi again @lmbdev. Just to be clear, we don't maintain that repository. It's possible that the bug exists only there, so it would save time and effort if you can show us a functional example of the issue using the official code from this repository (not a screenshot). We recommend using JSFiddle. Thanks again!

**Comment by usmonster** [comment]
I'll close this due to inactivity and because it seems to come from a fork, not from the official plugin. I may reopen it if new information arises.
