### ISSUE TITLE
The button in navigation doubles

### ISSUE THREAD

**Issue by katemariam** [taitems/jQuery.Gantt#230]
![image](https://user-images.githubusercontent.com/46659686/52683101-bde71900-2f7c-11e9-95fc-17d0ad6c7938.png)

Anyone experienced this? My buttons on my navigation doubles. What may be the problem?

**Comment by usmonster** [comment]
Hello! Thanks for the report.

I haven't seen this before, but I notice that the dates and weekday header text also looks misaligned... It looks like it may be an issue with the CSS on the page—perhaps there are some rules that interfere with the chart's styles?

Perhaps you can inspect some elements and see if any chart style is pointing to an unexpected rule?

**Comment by katemariam** [comment]
Thanks! I figured it has a conflict with the bootstrap that i import. It works fine with bootstrap 3 :> Thanks for the answer.

**Comment by usmonster** [comment]
You're welcome! I'll close the issue now, but feel free to reopen with more information if you think there's anything that should change in the CSS of the plug-in. :)
