### ISSUE TITLE
how can I draw a gantt in minutes

### ISSUE THREAD

**Issue by wangyunyuns** [taitems/jQuery.Gantt#231]

**Comment by usmonster** [comment]
Hello, and thanks for asking!

Today, it's not possible to see minute-level precision with the plugin.

If you want minutes to be taken into account in the hour scale, you can subscribe to #47 to know when it's implemented.

_(Note: If you want a separate scale/zoom level for minute-level precision, i.e. #159, you may want to find or create a fork that does this.)_

I hope this helps! (Closing this issue for now, but I can reopen if it's not clear.)
