### ISSUE TITLE
Finer scaling

### ISSUE THREAD

**Issue by DBX12** [taitems/jQuery.Gantt#236]
Would it be possible to implement finer scaling (down to minutes or at least quarters of an hour)? Some tasks in my project are really small and take less than an hour and it would be great if I could display it correctly.

**Comment by usmonster** [comment]
Hi, and thanks for using the plugin and taking the time to ask your question here.

For the moment, we're not considering adding new scale views (eg. a dedicated "minutes" scale), but the fix to #47 should make the existing hours scale more usable for your case.

For now, you can subscribe to that issue to follow its progress, and I'll close this one. (Feel free to comment if you feel this should be reopened.)
