### ISSUE TITLE
How to configure to use higher zoom out  level by default during initial load of the chart 

### ISSUE THREAD

**Issue by keatchong** [taitems/jQuery.Gantt#238]
Hi

I am using the library to draw gantt chart,  one of the feedback i got from testers is that they want the initial  rendering to be at higher zoom level especially in scenario not many tasks are being keyed in and they are in short interval. Is there a way to change the default setting ?

Thanks

Keat

**Comment by mikeott** [comment]
Try this:

    `scale: "weeks"`

Options are:

- hrs
- days
- weeks
- months

**Comment by usmonster** [comment]
You can set the initial scale explicitly, as @mikeott mentions—the documentation can be found here:
http://taitems.github.io/jQuery.Gantt/#config

In case you want a way to "auto scale" the initial rendering of the chart, you might be interested to subscribe to #84.

I'll close this issue for now, but feel free to comment again if your question isn't answered. Thanks for using the chart and for taking the time to ask your question (and sorry for the delayed response)!
