### ISSUE TITLE
Can we show minutes as minscale

### ISSUE THREAD

**Issue by jasjitCheema** [taitems/jQuery.Gantt#244]
Thanks for you your quick fix from last issue.

Can we save the date time in minutes as well as e.g. From 12:30 to 1:30

**Comment by usmonster** [comment]
Hello again, and thanks for asking 😄 

There's currently no plan to support a minutes-level scale (see #159 for the discussion), but #47 should cover your use case. You can subscribe to that issue to know when it's implemented & released.

I'll close this one for now, but please feel to reopen or comment if you have any other related questions.
