### ISSUE TITLE
Would you like to add a license file?

### ISSUE THREAD

**Issue by chick-p** [taitems/jQuery.Gantt#249]
I know that this jQuery.Gannt is MIT License from README.md
On the other hand, GitHub guides to add a license file.
https://docs.github.com/ja/github/creating-cloning-and-archiving-repositories/licensing-a-repository
I would appreciate it if you could add a license file.

Thanks!

**Comment by usmonster** [comment]
Sure! I can do it, but you can also feel free to open a pull request. 🙂  Thanks for your contribution!

**Comment by chick-p** [comment]
Thank you for your response!
I've opened a pull request as https://github.com/taitems/jQuery.Gantt/pull/250.

**Comment by taitems** [comment]
Closed by #250 :)
