### ISSUE TITLE
How to use the functions onItemClick: function(data) and $(".gantt").popover({

### ISSUE THREAD

**Issue by clausowitz** [taitems/jQuery.Gantt#252]
I succesfully implemented the jQuery Gantt on my sharepoint list. Now I would like to use the onItemClick function and the popover function. How do I change alert("Item clicked - show some details"); to something more meaningfull like opening the list item in another page?
I tried following but I get an error saying Unable to get property 'itemData' of undefined or null reference
onItemClick: function(data) {
			var itemData = data.itemData;
            		var itemElement = data.itemElement;
            		var itemIndex = data.itemIndex;
                        console.log(itemData);
	                alert(itemData);
                },

Furthermore I would like to change the popover. Showing the Title in the popup is helpful but the content displaying content: "Here's some useful information.", I would like to show some more info from the listitem.

**Comment by usmonster** [comment]
Hi, and sorry for the huge respoonse latency! Thanks for asking your questions here.

To clarify your first issue, the `data` parameter will only be present if you include a `dataObj` in the [values](https://taitems.github.io/jQuery.Gantt/#values) you use to populate the chart.

To answer your second question, the popover functionality you see in the demo comes strictly from [a separate Bootstrap plugin](https://getbootstrap.com/docs/3.4/javascript/#popovers) and has no related code in the Gantt plugin itself. You can see in the demo page [how we get the title](https://github.com/taitems/jQuery.Gantt/blob/master/index.html#L613), and you can do something similar to show custom content by getting the data directly off the element.

Hope this helps!
