### ISSUE TITLE
Is it possible to drag single tasks in the timeline?

### ISSUE THREAD

**Issue by jmherzog-de** [taitems/jQuery.Gantt#253]
I'm currently working on a project with this library and I have to implement a drag and drop feature for the tasks, but the documentation doesn't give any hint on how to do this. Is it already possible to drag tasks on the Gantt chart? I think this would be a really nice feature for further releases.

**Comment by usmonster** [comment]
Sorry for thee delay, but there's currently no built-in way to graphically edit the chart items—please see #136 for details, and don't forget to subscribe to the issue for any future updates on the topic! (I'll close this one as a duplicate.)
