### ISSUE TITLE
Multiple items on a row.

### ISSUE THREAD

**Issue by Ganglegreen** [taitems/jQuery.Gantt#58]
Awesome edition of jQuery.Gantt.  Thank you.

Is it possible to put multiple items on a single row?

When I tried every combination I can think of, I can't get it to not insert an additional row for each item.

Application is scheduling when Positions are on the left and time on top.

Would like to have one line per left item and multiple items across for sched entries.

I can do it on some versions of jQuery.Gantt, but yours has great features/documentation and would be  ideal if I could figure that out.

Thank you in advance for any feedback.

Figured it out - It has to be in the array for the row - all set.

**Comment by portnull** [comment]
This just helped me a lot, thank you.

**Comment by reustle** [comment]
For people finding this, I wanted to add a readable version of the example by @Alplob 

```
source: [{
    name: "Sprint 0",
    desc: "Analysis",
    values: [{
        from: "/Date(1320192000000)/",
        to: "/Date(1322401600000)/",
        label: "Requirement Gathering",
        customClass: "ganttRed"
    },{
        from: "/Date(1322611200000)/",
        to: "/Date(1323902400000)/",
        label: "Scoping",
        customClass: "ganttRed"
    }]
}]
```

**Comment by usmonster** [comment]
This is functionality (and much more) is documented in the [upcoming version](/taitems/jQuery.Gantt/commit/5776d00#diff-eacf331f0ffc35d4b482f1d15a887d3bR378).
