### ISSUE TITLE
I've tried really hard to get this working with .NET MVC, but the JSON response never seems to be in the right format. I've tried formatting the data as a string, but that doesnt seem to work either. Has anyone else got this working with MVC?

### ISSUE THREAD

**Issue by jimdunstan** [taitems/jQuery.Gantt#68]

**Comment by SirGrowns** [comment]
I've just had this issue and solved it by adding to this: create: function (element) { ***

inside $.getJSON change to the following:
var parsed = JSON.parse(jsData);

element.data = parsed;
core.init(element);
